# Generated by Django 4.1.4 on 2023-02-03 03:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brogram_times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_name', models.CharField(max_length=50)),
                ('time_start_from', models.TimeField()),
                ('time_end_in', models.TimeField()),
                ('time_is_active', models.BooleanField(default=True)),
                ('time_published_in', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 6, 47, 17, 266632))),
                ('time_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brogram_lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_day', models.CharField(choices=[('الأحد', 'الأحد'), ('الإثنين', 'الإثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس')], max_length=20)),
                ('lesson_is_active', models.BooleanField(default=True)),
                ('lesson_published_in', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 6, 47, 17, 266632))),
                ('lesson_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_classes')),
                ('lesson_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_sections')),
                ('lesson_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_stages')),
                ('lesson_study_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_study_terms')),
                ('lesson_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_subjects')),
                ('lesson_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool_brogram.brogram_times')),
            ],
        ),
    ]
