# Generated by Django 4.1.4 on 2023-01-21 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scool_brogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brogram_lessons',
            name='lesson_day',
            field=models.CharField(choices=[('الأحد', 'الأحد'), ('الإثنين', 'الإثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس')], max_length=20),
        ),
        migrations.AlterField(
            model_name='brogram_times',
            name='time_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 2, 0, 42, 36421)),
        ),
        migrations.DeleteModel(
            name='Brogram_days',
        ),
    ]
