# Generated by Django 4.1.4 on 2023-04-25 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scool_brogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brogram_lessons',
            name='lesson_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 23, 32, 48, 98215)),
        ),
        migrations.AlterField(
            model_name='brogram_times',
            name='time_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 23, 32, 48, 98215)),
        ),
    ]
