# Generated by Django 4.1.4 on 2023-01-24 13:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scool_brogram', '0002_alter_brogram_lessons_lesson_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brogram_lessons',
            name='lesson_created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brogram_lessons',
            name='lesson_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brogram_lessons',
            name='lesson_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 16, 55, 16, 104374)),
        ),
        migrations.AlterField(
            model_name='brogram_times',
            name='time_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 16, 55, 16, 104374)),
        ),
    ]
