# Generated by Django 4.1.4 on 2023-01-24 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scool_brogram', '0003_brogram_lessons_lesson_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brogram_lessons',
            old_name='leson_subject',
            new_name='lesson_subject',
        ),
        migrations.AlterField(
            model_name='brogram_lessons',
            name='lesson_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 17, 4, 3, 525346)),
        ),
        migrations.AlterField(
            model_name='brogram_times',
            name='time_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 17, 4, 3, 525346)),
        ),
    ]
