# Generated by Django 4.1.4 on 2023-01-25 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scool_brogram', '0004_rename_leson_subject_brogram_lessons_lesson_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brogram_lessons',
            name='lesson_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 18, 51, 36, 853934)),
        ),
        migrations.AlterField(
            model_name='brogram_times',
            name='time_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 18, 51, 36, 853934)),
        ),
    ]
