# Generated by Django 4.1.4 on 2023-01-30 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scool_brogram', '0007_alter_brogram_lessons_lesson_published_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brogram_lessons',
            name='lesson_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 22, 57, 13, 801797)),
        ),
        migrations.AlterField(
            model_name='brogram_times',
            name='time_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 22, 57, 13, 801797)),
        ),
    ]
