# Generated by Django 4.1.4 on 2023-01-02 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_is_active', models.BooleanField(default=True)),
                ('category_publish_in', models.DateTimeField(default=datetime.datetime(2023, 1, 2, 20, 31, 16, 381163))),
            ],
        ),
    ]
