# Generated by Django 4.1.4 on 2023-01-12 23:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_is_active', models.BooleanField(default=True)),
                ('book_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 13, 2, 1, 13, 148475))),
            ],
        ),
        migrations.CreateModel(
            name='Books_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_is_active', models.BooleanField(default=True)),
                ('class_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 13, 2, 1, 13, 148475))),
                ('class_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Books_stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50)),
                ('stage_is_active', models.BooleanField(default=True)),
                ('stage_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 13, 2, 1, 13, 148475))),
                ('stage_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Books_study_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_term_name', models.CharField(max_length=50)),
                ('study_term_is_active', models.BooleanField(default=True)),
                ('study_term_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 13, 2, 1, 13, 148475))),
                ('study_term_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_classes')),
                ('study_term_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study_term_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_stages')),
            ],
        ),
        migrations.CreateModel(
            name='Books_urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_url_name', models.CharField(max_length=50)),
                ('book_url_type', models.CharField(choices=[('docx', 'docx'), ('pdf', 'pdf')], max_length=10)),
                ('book_url', models.URLField()),
                ('book_url_is_active', models.BooleanField(default=True)),
                ('book_url_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 13, 2, 1, 13, 148475))),
                ('book_url_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('book_url_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_classes')),
                ('book_url_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_url_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_stages')),
                ('book_url_study_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_study_terms')),
            ],
        ),
        migrations.CreateModel(
            name='Books_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_file_name', models.CharField(max_length=50)),
                ('book_file_type', models.CharField(choices=[('docx', 'docx'), ('pdf', 'pdf')], max_length=10)),
                ('book_file', models.FileField(upload_to='')),
                ('book_file_is_active', models.BooleanField(default=True)),
                ('book_file_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 13, 2, 1, 13, 148475))),
                ('book_file_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('book_file_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_classes')),
                ('book_file_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_file_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_stages')),
                ('book_file_study_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_study_terms')),
            ],
        ),
        migrations.AddField(
            model_name='books_classes',
            name='class_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_stages'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_classes'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='books',
            name='book_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_stages'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_study_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_study_terms'),
        ),
    ]
