# Generated by Django 4.1.4 on 2023-01-15 11:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_classes',
            name='class_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 14, 58, 13, 348620)),
        ),
        migrations.AlterField(
            model_name='books_files',
            name='book_file_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 14, 58, 13, 348620)),
        ),
        migrations.AlterField(
            model_name='books_stages',
            name='stage_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 14, 58, 13, 348620)),
        ),
        migrations.AlterField(
            model_name='books_study_terms',
            name='study_term_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 14, 58, 13, 348620)),
        ),
        migrations.AlterField(
            model_name='books_urls',
            name='book_url_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 14, 58, 13, 348620)),
        ),
        migrations.CreateModel(
            name='Books_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_is_active', models.BooleanField(default=True)),
                ('book_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 15, 14, 58, 13, 348620))),
                ('book_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_classes')),
                ('book_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_stages')),
                ('book_study_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_study_terms')),
            ],
        ),
        migrations.AlterField(
            model_name='books_files',
            name='book_file_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_books'),
        ),
        migrations.AlterField(
            model_name='books_urls',
            name='book_url_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books_books'),
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
