# Generated by Django 4.1 on 2022-09-20 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_books_books',
            name='book_published_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 453424)),
        ),
        migrations.AlterField(
            model_name='pdf_books_classes',
            name='class_published_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 453424)),
        ),
        migrations.AlterField(
            model_name='pdf_books_stages',
            name='stage_published_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 453424)),
        ),
        migrations.AlterField(
            model_name='pdf_books_study_terms',
            name='study_term_published_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 453424)),
        ),
    ]
