# Generated by Django 4.1 on 2022-09-20 05:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_books_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_is_active', models.BooleanField(default=True)),
                ('book_published_in', models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 453424))),
            ],
        ),
        migrations.CreateModel(
            name='Audio_books_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_is_active', models.BooleanField(default=True)),
                ('class_published_in', models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 453424))),
            ],
        ),
        migrations.CreateModel(
            name='Audio_books_stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50)),
                ('stage_is_active', models.BooleanField(default=True)),
                ('stage_published_in', models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 453424))),
            ],
        ),
        migrations.CreateModel(
            name='Audio_books_study_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_term_name', models.CharField(max_length=50)),
                ('study_term_is_active', models.BooleanField(default=True)),
                ('study_term_published_in', models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 453424))),
                ('study_term_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_classes')),
                ('study_term_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_stages')),
            ],
        ),
        migrations.CreateModel(
            name='Audio_books_units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_is_active', models.BooleanField(default=True)),
                ('unit_published_in', models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 453424))),
                ('unit_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_books')),
                ('unit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_classes')),
                ('unit_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_stages')),
                ('unit_study_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_study_terms')),
            ],
        ),
        migrations.CreateModel(
            name='Audio_books_lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50)),
                ('lesson_is_active', models.BooleanField(default=True)),
                ('lesson_published_in', models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 453424))),
                ('lesson_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_books')),
                ('lesson_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_classes')),
                ('lesson_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_stages')),
                ('lesson_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_units')),
                ('lisson_study_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_study_terms')),
            ],
        ),
        migrations.AddField(
            model_name='audio_books_classes',
            name='class_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_stages'),
        ),
        migrations.AddField(
            model_name='audio_books_books',
            name='book_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_classes'),
        ),
        migrations.AddField(
            model_name='audio_books_books',
            name='book_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_stages'),
        ),
        migrations.AddField(
            model_name='audio_books_books',
            name='book_study_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_books.audio_books_study_terms'),
        ),
    ]
