# Generated by Django 4.1.4 on 2023-01-21 17:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scool', '0011_alter_scool_classes_class_published_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons_urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=250)),
                ('url_type', models.CharField(choices=[('docx', 'docx'), ('pdf', 'pdf'), ('audio', 'audio'), ('vidio', 'vidio')], max_length=10)),
                ('url', models.URLField()),
                ('url_is_active', models.BooleanField(default=True)),
                ('url_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 21, 20, 32, 34, 875326))),
                ('url_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_classes')),
                ('url_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('url_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_lessons')),
                ('url_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_stages')),
                ('url_study_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_study_terms')),
                ('url_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_subjects')),
                ('url_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_units')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('file_type', models.CharField(choices=[('docx', 'docx'), ('pdf', 'pdf'), ('audio', 'audio'), ('vidio', 'vidio')], max_length=10)),
                ('file', models.FileField(upload_to='')),
                ('file_is_active', models.BooleanField(default=True)),
                ('file_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 21, 20, 32, 34, 875326))),
                ('file_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_classes')),
                ('file_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_lessons')),
                ('file_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_stages')),
                ('file_study_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_study_terms')),
                ('file_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_subjects')),
                ('file_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_units')),
            ],
        ),
    ]
