# Generated by Django 4.1.4 on 2023-04-25 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons_files',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='lessons_files',
            name='file_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 23, 32, 48, 82579)),
        ),
        migrations.AlterField(
            model_name='lessons_urls',
            name='url_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 23, 32, 48, 82579)),
        ),
    ]
