# Generated by Django 4.1.4 on 2023-01-25 15:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forums',
            name='forum_created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forums',
            name='forum_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forums',
            name='forum_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 18, 51, 36, 853934)),
        ),
        migrations.CreateModel(
            name='Forums_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=250)),
                ('post_content', models.TextField()),
                ('post_is_active', models.BooleanField(default=True)),
                ('posted_by', models.CharField(max_length=50)),
                ('forum_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 25, 18, 51, 36, 853934))),
                ('post_cforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.forums')),
                ('post_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
