# Generated by Django 4.1.4 on 2023-01-25 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_forums_forum_created_by_forums_forum_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forums_posts',
            old_name='post_cforum',
            new_name='post_forum',
        ),
        migrations.AlterField(
            model_name='forums',
            name='forum_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 18, 59, 9, 300365)),
        ),
        migrations.AlterField(
            model_name='forums_posts',
            name='forum_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 18, 59, 9, 300365)),
        ),
    ]
