# Generated by Django 4.1.4 on 2023-01-29 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_rename_post_cforum_forums_posts_post_forum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forums_posts',
            name='forum_published_in',
        ),
        migrations.AddField(
            model_name='forums_posts',
            name='post_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 23, 38, 36, 347588)),
        ),
        migrations.AlterField(
            model_name='forums',
            name='forum_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 23, 38, 36, 347588)),
        ),
    ]
