# Generated by Django 4.1 on 2022-09-19 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docx_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docx_books_books',
            name='book_published_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 11, 25, 23, 855280)),
        ),
        migrations.AlterField(
            model_name='docx_books_classes',
            name='class_published_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 11, 25, 23, 855280)),
        ),
        migrations.AlterField(
            model_name='docx_books_stages',
            name='stage_published_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 11, 25, 23, 755001)),
        ),
        migrations.AlterField(
            model_name='docx_books_study_terms',
            name='study_term_published_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 11, 25, 23, 855280)),
        ),
    ]
