# Generated by Django 4.1 on 2022-09-20 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docx_books', '0002_alter_docx_books_books_book_published_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docx_books_books',
            name='book_published_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 437797)),
        ),
        migrations.AlterField(
            model_name='docx_books_classes',
            name='class_published_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 437797)),
        ),
        migrations.AlterField(
            model_name='docx_books_stages',
            name='stage_published_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 337540)),
        ),
        migrations.AlterField(
            model_name='docx_books_study_terms',
            name='study_term_published_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 8, 33, 32, 437797)),
        ),
    ]
