# Generated by Django 4.1.4 on 2022-12-30 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newz_articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200)),
                ('article_content', models.TextField()),
                ('article_is_active', models.BooleanField(default=True)),
                ('article_publish_in', models.DateTimeField(default=datetime.datetime(2022, 12, 30, 10, 0, 38, 134581))),
            ],
        ),
        migrations.CreateModel(
            name='Newz_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_is_active', models.BooleanField(default=True)),
                ('category_publish_in', models.DateTimeField(default=datetime.datetime(2022, 12, 30, 10, 0, 38, 134581))),
            ],
        ),
        migrations.DeleteModel(
            name='newz_article',
        ),
        migrations.DeleteModel(
            name='Newz_category',
        ),
        migrations.AddField(
            model_name='newz_articles',
            name='article_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newz.newz_categories'),
        ),
    ]
