# Generated by Django 4.1.4 on 2023-01-20 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newz', '0016_alter_newz_articles_article_publish_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newz_articles',
            name='article_publish_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 1, 3, 54, 85954)),
        ),
        migrations.AlterField(
            model_name='newz_categories',
            name='category_publish_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 1, 3, 54, 85954)),
        ),
    ]
