# Generated by Django 4.1.4 on 2023-02-03 03:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_is_active', models.BooleanField(default=True)),
                ('class_published_in', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 6, 47, 17, 249943))),
                ('class_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School_stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50)),
                ('stage_is_active', models.BooleanField(default=True)),
                ('stage_published_in', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 6, 47, 17, 249943))),
                ('stage_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School_study_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_term_name', models.CharField(max_length=50)),
                ('study_term_is_active', models.BooleanField(default=True)),
                ('study_term_published_in', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 6, 47, 17, 249943))),
                ('study_term_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_classes')),
                ('study_term_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study_term_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_stages')),
            ],
        ),
        migrations.CreateModel(
            name='School_subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_is_active', models.BooleanField(default=True)),
                ('subject_published_in', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 6, 47, 17, 249943))),
                ('subject_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_classes')),
                ('subject_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_stages')),
                ('subject_study_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_study_terms')),
            ],
        ),
        migrations.CreateModel(
            name='School_units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_is_active', models.BooleanField(default=True)),
                ('unit_published_in', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 6, 47, 17, 249943))),
                ('unit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_classes')),
                ('unit_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_stages')),
                ('unit_study_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_study_terms')),
                ('unit_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_subjects')),
            ],
        ),
        migrations.CreateModel(
            name='School_sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('section_is_active', models.BooleanField(default=True)),
                ('section_published_in', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 6, 47, 17, 249943))),
                ('section_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_classes')),
                ('section_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_stages')),
            ],
        ),
        migrations.CreateModel(
            name='School_lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50)),
                ('lesson_is_active', models.BooleanField(default=True)),
                ('lesson_published_in', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 6, 47, 17, 249943))),
                ('lesson_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_classes')),
                ('lesson_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_stages')),
                ('lesson_study_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_study_terms')),
                ('lesson_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_subjects')),
                ('lesson_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_units')),
            ],
        ),
        migrations.AddField(
            model_name='school_classes',
            name='class_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.school_stages'),
        ),
    ]
