# Generated by Django 4.1.4 on 2023-01-18 21:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scool_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_is_active', models.BooleanField(default=True)),
                ('class_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 19, 0, 57, 44, 845797))),
                ('class_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scool_stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50)),
                ('stage_is_active', models.BooleanField(default=True)),
                ('stage_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 19, 0, 57, 44, 845797))),
                ('stage_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scool_study_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_term_name', models.CharField(max_length=50)),
                ('study_term_is_active', models.BooleanField(default=True)),
                ('study_term_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 19, 0, 57, 44, 861422))),
                ('study_term_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scool_units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_is_active', models.BooleanField(default=True)),
                ('unit_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 19, 0, 57, 44, 861422))),
                ('unit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_classes')),
                ('unit_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_stages')),
                ('unit_study_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_study_terms')),
            ],
        ),
        migrations.CreateModel(
            name='Scool_subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_is_active', models.BooleanField(default=True)),
                ('subject_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 19, 0, 57, 44, 861422))),
                ('subject_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_classes')),
                ('subject_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_stages')),
            ],
        ),
        migrations.CreateModel(
            name='Scool_sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('section_is_active', models.BooleanField(default=True)),
                ('section_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 19, 0, 57, 44, 845797))),
                ('section_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_classes')),
                ('section_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_stages')),
            ],
        ),
        migrations.CreateModel(
            name='Scool_lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50)),
                ('lesson_is_active', models.BooleanField(default=True)),
                ('lesson_published_in', models.DateTimeField(default=datetime.datetime(2023, 1, 19, 0, 57, 44, 861422))),
                ('lesson_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_classes')),
                ('lesson_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scool_classes',
            name='class_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scool.scool_stages'),
        ),
    ]
