# Generated by Django 4.1.4 on 2023-04-25 20:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school_classes',
            options={'verbose_name': 'صف دراسي', 'verbose_name_plural': 'الصفوف الدراسية'},
        ),
        migrations.AlterModelOptions(
            name='school_lessons',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'الدروس'},
        ),
        migrations.AlterModelOptions(
            name='school_sections',
            options={'verbose_name': 'شعبة', 'verbose_name_plural': 'الشعب'},
        ),
        migrations.AlterModelOptions(
            name='school_stages',
            options={'verbose_name': 'مرحلة دراسية', 'verbose_name_plural': 'المراحل الدراسية'},
        ),
        migrations.AlterModelOptions(
            name='school_study_terms',
            options={'verbose_name': 'فصل دراسي', 'verbose_name_plural': 'الفصول الدراسية'},
        ),
        migrations.AlterModelOptions(
            name='school_subjects',
            options={'verbose_name': 'مادة', 'verbose_name_plural': 'المواد'},
        ),
        migrations.AlterModelOptions(
            name='school_units',
            options={'verbose_name': 'وحدة دراسية', 'verbose_name_plural': 'الوحدات الدراسية'},
        ),
        migrations.AlterField(
            model_name='school_classes',
            name='class_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 23, 32, 48, 82579)),
        ),
        migrations.AlterField(
            model_name='school_lessons',
            name='lesson_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 23, 32, 48, 82579)),
        ),
        migrations.AlterField(
            model_name='school_sections',
            name='section_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 23, 32, 48, 82579)),
        ),
        migrations.AlterField(
            model_name='school_stages',
            name='stage_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 23, 32, 48, 82579)),
        ),
        migrations.AlterField(
            model_name='school_study_terms',
            name='study_term_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 23, 32, 48, 82579)),
        ),
        migrations.AlterField(
            model_name='school_subjects',
            name='subject_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school_subjects',
            name='subject_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 23, 32, 48, 82579)),
        ),
        migrations.AlterField(
            model_name='school_units',
            name='unit_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 23, 32, 48, 82579)),
        ),
    ]
