# Generated by Django 4.1.4 on 2023-01-18 22:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scool', '0002_scool_lessons_lesson_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scool_lessons',
            name='lesson_study_term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scool.scool_study_terms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scool_lessons',
            name='lesson_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scool.scool_subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scool_lessons',
            name='lesson_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scool.scool_units'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scool_classes',
            name='class_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 1, 33, 5, 664851)),
        ),
        migrations.AlterField(
            model_name='scool_lessons',
            name='lesson_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 1, 33, 5, 664851)),
        ),
        migrations.AlterField(
            model_name='scool_sections',
            name='section_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 1, 33, 5, 664851)),
        ),
        migrations.AlterField(
            model_name='scool_stages',
            name='stage_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 1, 33, 5, 664851)),
        ),
        migrations.AlterField(
            model_name='scool_study_terms',
            name='study_term_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 1, 33, 5, 664851)),
        ),
        migrations.AlterField(
            model_name='scool_subjects',
            name='subject_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 1, 33, 5, 664851)),
        ),
        migrations.AlterField(
            model_name='scool_units',
            name='unit_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 1, 33, 5, 664851)),
        ),
    ]
