# Generated by Django 4.1.4 on 2023-02-01 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scool', '0019_alter_scool_classes_class_published_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scool_classes',
            name='class_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 10, 8, 25, 329093)),
        ),
        migrations.AlterField(
            model_name='scool_lessons',
            name='lesson_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 10, 8, 25, 329093)),
        ),
        migrations.AlterField(
            model_name='scool_sections',
            name='section_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 10, 8, 25, 329093)),
        ),
        migrations.AlterField(
            model_name='scool_stages',
            name='stage_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 10, 8, 25, 329093)),
        ),
        migrations.AlterField(
            model_name='scool_study_terms',
            name='study_term_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 10, 8, 25, 329093)),
        ),
        migrations.AlterField(
            model_name='scool_subjects',
            name='subject_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 10, 8, 25, 329093)),
        ),
        migrations.AlterField(
            model_name='scool_units',
            name='unit_published_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 10, 8, 25, 329093)),
        ),
    ]
